### PR TITLE
Limit config translation

### PR DESCRIPTION
**Pull request by grezniczek**
Translation of `config.json` via the _tt__ prefix would allow to translate anything, including items that should not be translated (as author details) and items that must not be translated (such as keys). 

In order to avoid confusion and potential misuse, this PR limits the applicabilty of config translations by providing a whitelist of keys and a blacklist of sections.

### CODE REVIEW

**Comment by mmcev106** [comment]
It looks like merging this broken the `testTranslateConfig()` unit test for translating project setting names.  Is that valid use case?

**Comment by grezniczek** [comment]
I'll check.

**Comment by grezniczek** [comment]
I found the bug ... see #272

**Comment by mmcev106** [comment]
It also looks like our code scanner detected that array constants are not allowed in PHP 5.5...  Do you mind converting those to variables?  It might be time to time to ask Rob about bumping the REDCap minimum up to 5.6...

**Comment by grezniczek** [comment]
Done. #273

**Pull request merged**
