### PR TITLE
Adding new param to getUrl() method to return alternative API endpoint

### PR DESCRIPTION
**Pull request by taylorr4**
Adding new param to getUrl() method to return an alternative form of the URL that does not contain the REDCap version directory (e.g., https://example.com/redcap/redcap_vX.X.X/ExternalModules/?id=1&page=index&pid=33), in which setting $useApiEndpoint=true will return a version-less URL using the API end-point (e.g., https://example.com/redcap/api/?type=module&id=1&page=index&pid=33). Both links will work identically. Also, this alternate API URL works for non-PHP files too, such as CSS and JS. NOTE: This is mainly being added for when External Modules gets added inside the REDCap release in the future where it will be inside the REDCap version folder. This API endpoint will work in REDCap 7.6.8 and later.

### CODE REVIEW

**Comment by mmcev106** [comment]
It looks like this pull request has some conflicts with some recent changes.  Are you able to merge the latest version of the testing branch into this one and resolve those conflicts?

Do you have to deal with conflicts often?  If not, I typically use p4merge to do visual three-way merge for conflicts.  Let me know if you want to see it in action.

**Comment by taylorr4** [comment]
I deal with conflicts sometimes, but you probably know this codebase better than me. So go ahead and feel free to merge it however you see fit. Thanks!

**Comment by taylorr4** [comment]
@mmcev106 I had a chance to take a look at these and resolve them, so they're ready to merge when you're able.

**Comment by mmcev106** [comment]
Some changes were overwritten during a merge on this pull request.  I have cherry-picked the only non-merge commit in this branch (4a28181) into the testing branch (as commit e3797d2).  That means the changes in this branch are effectively merged, but I can closing this pull request without merging it.

**Pull request closed without merging**
