### PR TITLE
Adding cron job functionality for modules

### PR DESCRIPTION
**Pull request by taylorr4**
If any cron jobs are defined in the config.json when a module is enabled, those jobs will get added as new rows in REDCap's redcap_crons table. The cron_frequency and cron_max_run_time must be defined as integers (in units of seconds), and all attributes must be provided, else an exception is thrown, thus preventing the module from being enabled. 

The cron_max_run_time refers to the maximum time that the cron job is expected to run (once that time is passed, if the cron is still listed as processing, it assumes it has failed/crashed and thus will automatically enable it to run again at the next scheduled interval). The "method" attribute corresponds to a method in the module class. 

**Note: This External Module cron job functionality will only function in REDCap 7.6.6 and higher.**

Example config format for module crons. 
```
{
	"name": "Name of the module",
	...
	"crons": [
		{
			"cron_name": "cron1",
			"cron_description": "Cron that runs every 30 minutes to do X",
			"method": "cron1",
			"cron_frequency": "1800",
			"cron_max_run_time": "60"
		 },
		{
			"cron_name": "cron2",
			"cron_description": "Cron that runs daily to do Y",
			"method": "some_other_method",
			"cron_frequency": "86400",
			"cron_max_run_time": "1200"
		 }
	]
}

```

### CODE REVIEW

**Comment by 123andy** [comment]
Awesome!

**Comment by mmcev106** [comment]
Very cool!!!  I can't wait to give it a whirl.

**Comment by mmcev106** [comment]
This request has been merged!   Thanks very much.  Per chance, is it worth your time to add an example cron to the configuration example module and/or the README documentation?

**Comment by taylorr4** [comment]
@mmcev106, yes, indeed. I'll work on that. Thanks!

**Comment by 123andy** [comment]
If a module is deleted, is the corresponding cron entry in the crons table cleaned up somehow?  What about if the module is disabled?  Will that prevent the cron from firing or are we relying on the EM code to do that?

**Comment by taylorr4** [comment]
If a module that was downloaded from the REDCap Repo (central repository) is disabled via the UI, then the crons get deleted from the crons table, and if it gets re-enabled, the crons get re-added. But if the module directory was deleted via the backend, then the crons would remain and be orphaned. One of the few things left on my to-do list is to build a new REDCap cron job that validates module crons to make sure they are in still sync, either for the reason of backend deletion OR in case someone modifies the config via backend methods on the server *after* the module has been enabled. So this new cron would keep all the module crons in sync to prevent issues like these. So i feel comfortable that we're covering our bases here.

**Comment by 123andy** [comment]
awesome

**Pull request merged**
